CONFIG_PMW3610_MACCEL=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=8
CONFIG_PMW3610_MACCEL_ROUNDING_CARRY_TIMEOUT_MS=2000

CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_SLEEP=n

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Enable SPI for PMW3610 trackball
CONFIG_SPI=y
CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=1200
# Other common PMW3610 settings
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_PMW3610_INVERT_X=y
