CONFIG_PMW3610_MACCEL=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=8
CONFIG_PMW3610_MACCEL_ROUNDING_CARRY_TIMEOUT_MS=2000

CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_SLEEP=n

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Enable SPI for trackball
CONFIG_SPI=y
